
[[lamassa-s82-x-ray-catalog-versus-ukidss]]
= LaMassa S82 (x-ray) catalog _versus_ UKIDSS

In this notebook the cross-matching procedure applied by
http://arxiv.org/abs/1510.00852[LaMassa et al. 2016] (LM hereafter) to
multi-wavelength catalogs will be reproduced. Particularly, we will
cross-match the x-ray data from XMM-Newton AO 13 cycle to UKIDSS
near-infrared. The goal here is to verify whether we can recover the
very same results therein, showing us our algorithm for Maximum
Likelihood Estimator to be correct.

The UKIDSS catalog here in use is the same used in LM: UKIDSS-LAS Data
Release 8, _primary_ objects, cleaned from spurious/noisy detections;
"?_apermag3_" magnitude measurements and accordingly errors were
retrieved. The table file `ukidss.fits` here used can be taken from
https://github.com/chbrandt/uks82[my github repository].

The LaMassa catalog --from where we'll take the x-ray sources-- was
downloaded from
http://vizier.u-strasbg.fr/viz-bin/VizieR?-source=J%2FApJ%2F817%2F172[CDS].

[[maximum-likelihood-estimator-mle]]
= Maximum Likelihood Estimator (MLE)

MLE is applied by LM to find the correct --or most possible--
counterpart to their x-ray sources. MLE was first proposed by
http://mnras.oxfordjournals.org/cgi/doi/10.1093/mnras/259.3.413[Sutherland
& Saunders in 1992] and is being adopted as a better alternative to the
simplistic _nearest-neighbour_ algorithm.

What MLE does is to estimate how probable a given counterpart candidate
is to be real counterpart from a source in its vicinity. The method was
developed having in mind that multiple candidates can be nearby in the
(RA,Dec) sky-projected plan. Accordingly, the method includes the
ancillary magnitudes as a third component to help differentiating
background objects from candidate(s).

Consider the situation where there is a source "S" (which was observed
by instrument "A") and in the vicinities, within a distance "da", of S
there are latexmath:[$N$] objects ("N1", "N2", ..., "NN") that were
observed by a different instrument ("B"). Also observed using "B", but
distant a bit further from "S". there are latexmath:[$M$] objects ("M1",
"M2", ..., "MM") that can not be related to "S", but will be of our help
further on. The "M" objects lie beyond the distance "da" and before
distance "db", and latexmath:[$db > da$]. _We want now to answer the
following question: which of the objects observed by "B" is in fact "S"
(observed by a different instrument)?_ Before coming with any answer, we
are taught that instruments "A" and "B" suffer from different physical
effects that lead to uncorrelated errors and different image resolutions
when registering the pictures; which means that "S" and its (true)
counterpart may _not_ be one over the other, but shifted by some amount.

The distance "da" from "S" is considered to be "vicinity", and objects
inside this distance are considered, _a priori_, candidates to the
(true) counterpart. Such objects will be called _ancillary_ objects. The
objects from sample `M` will be called _background_ objects, they
compose the sample of objects observed by "B" definitely _not_ candidate
to be "S" counterpart.

The MLE method will eventually give a score called _Reliability_
(latexmath:[$R$]) to each of the candidates. Such score --reliability--
is the probability of being the true counterpart, and is given by:
latexmath:[\[
R_j = \frac{LR_j}{\sum_j{LR_j}+(1-Q)}
\]]

The central figure in MLE is the likelihood ratio, latexmath:[$LR$]:
latexmath:[\[
LR_j = \frac{q(m) f(r)}{n(m)}
\]] .

latexmath:[$f(r)$] is the prior regarding the position of the candidate
object relative to the source. Typically, latexmath:[$f(r)$] is modelled
as a bidimensional Gaussian with latexmath:[$\sigma$] being the
quadrature sum of source's positional error and objects' average
positional error: latexmath:[\[
f(r) = \frac{1}{2 \pi \sigma} exp^{-r^2/2\sigma^2} ; 
\]] latexmath:[\[
\sigma = \frac{1}{2}\Big[\sqrt{\sigma^2_{\alpha_S} + \sigma^2_{\delta_S}} + \sqrt{\sigma^2_{\alpha_O} + \sigma^2_{\delta_O}}\Big]
\]]

latexmath:[$q(m)$] is the likelihood of the object being a (good)
candidate regarding its magnitude. It is computed by drawing the
ancillary objects normalized magnitude distribution and subtracting from
it the background objects normalized magnitude distribution.

Finally, latexmath:[$n(m)$] is the surface density of background objects
with magnitude latexmath:[$m$].It is computed by counting the number of
background objects per magnitude bin per square-degree; normalized by
the number of objects.

[[the-algorithm]]
== The algorithm

Let's put it all together to build an algorithm.

To compute MLE quantities we need to define the background and ancillary
samples. To do that we have to define the _search radius_
(latexmath:[$r_s$]) --from where the _ancillary_ sample will come out--
and the _inner & outer radii_ (latexmath:[$r_i$], latexmath:[$r_o$]) for
the background sample.

[[search-radii]]
=== Search radii

There are different ways to estimate the (best) _search radius_.
Typically, the instrument's (nominal) error radius, systematic plus
statistical, is used, as [LaMassa et al. 2016].
http://arxiv.org/abs/1603.08488[Timlin et al. 2016] have used the
Rayleigh Criterion to estimate such radius, considering then a physical
limitation on resolving close by objects; similarly, the overall PSF
(FWHM) is a valid estimator. Another way of estimating
latexmath:[$r_s$], data driven, is by directly estimating the typical
distance between the objects in each catalog.

Analogously, we have to define the _inner and outer radii_, from the
primary source, of the annulus defining the background region. Trully
speaking, the background region does _not_ need to be drawn as an
annulus centered centered in the source, but that is a straightforward,
generic choice for sampling background sources. It is important to
notice that the background region should avoid other sources' ancillary
sample, which is to say that the (annulus) region should not intersect
with another source's search area.

* Estimate samples radii
* (ancillary) search radius: latexmath:[$r_{s}$]
* background (annulus) radii: latexmath:[$r_{i} \lt r_{o}$]

[[samples-definition]]
=== Samples definition

Once we have the radii defined we cross-match the catalogs to define the
_ancillary_ and _background_ samples; At this point, each source has two
lists of objects linked to it:

* Source
* ancillary sample (within Rs)
* background sample (between Ri and Ro)

But before looping through each primary source, we may define
latexmath:[$q(m)$] and latexmath:[$n(m)$] as they are rather globally
defined functions. And after we have latexmath:[$q(m)$] we may estimate
latexmath:[$Q$].

* Estimate magnitude distributions
* latexmath:[$n(m)$]: background surface brightness distribution
* latexmath:[$q(m)$]: ancillary brightness distribution
* latexmath:[$Q$]: expected counterpart recover rate

[[radial-prior]]
==== Radial prior

The radial profile
latexmath:[$f(r) \propto \sigma^{-1} \exp^{-r^2/\sigma^2}$] is ideally
defined for each source, for latexmath:[$\sigma$] is a function of the
source' and ancillary objects' positional errors, latexmath:[$\sigma_s$]
and latexmath:[$\sigma_o$], resp.: latexmath:[\[
\sigma = \sqrt{\frac{\sigma_s^2 + \sigma_o^2}{2}}
\]]

If the positional errors are well behaved --i.e, their dispersion is
small--, we may approximate latexmath:[$f(r)$] as a global function. We
may consider latexmath:[$\sigma_s$] and latexmath:[$\sigma_o$] as the
mean of the respective positional errors.

* Compute mean positional errors
* primary sources catalog
* ancillary objects
* define latexmath:[$f(r)$]

[[likelood-ratio-threshold]]
==== Likelood Ratio threshold

The LR-threshold, latexmath:[$LR_{th}$], is the minimum value an
ancillary object may score to be considered a counterpart candidate.
There are different ways to compute latexmath:[$LR_{th}$], the simplest
one is based on the reliability parameter in a assintotic case: consider
there is only _one_ ancillary object within the _search radius_ around a
source; in this case we would expect such object to be the true source'
counterpart. Considering the Reliability parameter, latexmath:[$R$] a
probability score, latexmath:[$R_j=0.5$] is the minimal (reasonable)
value for such parameter so that the object can be considered a
candidate. Using the definition of latexmath:[$R$] above we should have:
latexmath:[\[
0.5 = \frac{LR_{th}}{LR_{th} + (1-Q)}
\]]

latexmath:[\[
LR_{th} = \frac{0.5(Q-1)}{-0.5}
\]]

latexmath:[\[
LR_{th} = 1-Q
\]]

[[counterpart-evaluation]]
=== Counterpart evaluation

Now that we have all the ingredients in place we may visit each primary
source' neighbourhood and evaluate each ancillary object.

For each source, * Loop over the respective ancillary sample: * evaluate
each object's latexmath:[$LR$] * remove objects with
latexmath:[$LR_j < LR_{th}$] * Sum all ancillaries' latexmath:[$LR_j$] *
Loop over all candidates: * compute latexmath:[$R_j$]

The highest latexmath:[$R_j$] is said to be the true counterpart.


+*In[1]:*+
[source, ipython3]
----
!ls *
----


+*Out[1]:*+
----
Untitled.ipynb

s82x:
chandra.dat  ReadMe  xmmao10.dat  xmmao13.dat

uks82:
Readme.md    ukidss_results3_2_34_51_409.fits	  v0.1
ukidss.fits  ukidss_results3_2_34_51_409.fits.gz  v0.2
----


+*In[2]:*+
[source, ipython3]
----
import booq
----


+*In[3]:*+
[source, ipython3]
----
from booq.table import ATable
----


+*In[4]:*+
[source, ipython3]
----
cat_lm = ATable.read('s82x/xmmao13.dat',readme='s82x/ReadMe',format='ascii.cds')
----


+*In[5]:*+
[source, ipython3]
----
cat_lm
----


+*Out[5]:*+
----
<ATable masked=True length=2862>
Seq
ObsID
RAdeg
DEdeg
e_Pos
DistNN
ExtFlag
InXMM
InChandra
FSoft
e_FSoft
CtSoft
SoftDetml
FHard
e_FHard
CtHard
HardDetml
FFull
e_FFull
CtFull
FullDetml
logLSoft
logLHard
logLFull
RejS
SDSS
RASdeg
DESdeg
RelS
rS
CoaddS
umag
e_umag
gmag
e_gmag
rmag
e_rmag
imag
e_imag
zmag
e_zmag
SpecID
Class
zsp
r_zsp
WISE
RAWdeg
DEWdeg
e_RAWdeg
e_DEWdeg
RelW
rW
W1mag
e_W1mag
W1SNR
W2mag
e_W2mag
W2SNR
W3mag
e_W3mag
W3SNR
W4mag
e_W4mag
W4SNR
ExtW
RejW
UKIDSS
RAUdeg
DEUdeg
RelU
rU
Ymag
e_Ymag
Jmag
e_Jmag
Hmag
e_Hmag
Kmag
e_Kmag
RejU
VHS
RAVdeg
DEVdeg
RelV
rV
JVmag
e_JVmag
HVmag
e_HVmag
KVmag
e_KVmag
RejV
GALEX
RAGdeg
DEGdeg
e_NUVPos
e_FUVPos
RelG
rG
NUV
e_NUV
FUV
e_FUV
FIRST
RAFdeg
DEFdeg
rF
F1.4GHz
e_F1.4GHz
RAHdeg
DEHdeg
rH
F250
e_F250
F350
e_F350
F500
e_F500
XMMAO10CP
ChCP
CPCoord
deg
deg
arcsec
arcsec
1e-17 W / m2
1e-17 W / m2
ct
1e-17 W / m2
1e-17 W / m2
ct
1e-17 W / m2
1e-17 W / m2
ct
[10-7W]
[10-7W]
[10-7W]
deg
deg
arcsec
mag
mag
mag
mag
mag
mag
mag
mag
mag
mag
deg
deg
arcsec
arcsec
arcsec
mag
mag
mag
mag
mag
mag
mag
mag
deg
deg
arcsec
mag
mag
mag
mag
mag
mag
mag
mag
deg
deg
arcsec
mag
mag
mag
mag
mag
mag
deg
deg
arcsec
arcsec
arcsec
mag
mag
mag
mag
deg
deg
arcsec
mJy
mJy
deg
deg
arcsec
mJy
mJy
mJy
mJy
mJy
mJy
int64
int64
float64
float64
float64
float64
int64
str8
str19
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str3
str19
float64
float64
float64
float64
str3
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str19
str6
float64
int64
str19
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str3
str3
str12
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str2
str12
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str2
str19
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str22
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
str1
str2
int64
2359
742830101
14.097
0.166
4.7
515.8
0
no
no
1.61
0.52
14.92
16.53
0.0
0.0
0.0
0.0
5.5
1.66
22.32
14.48
-999.0
-999.0
-999.0
no
1237663784203584096
14.097
0.166
0.82
1.97
no
22.98
0.3
22.76
0.12
22.94
0.19
22.49
0.18
22.67
0.57
--
--
-999.0
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2360
742830101
14.115
-0.353
3.5
171.7
0
no
no
1.68
0.38
30.6
33.04
0.0
0.0
0.0
0.0
6.39
1.26
51.67
33.41
-999.0
-999.0
-999.0
no
1237663783666712774
14.115
-0.352
0.98
3.42
no
21.87
0.24
20.39
0.03
18.93
0.02
18.33
0.01
17.9
0.03
--
--
-999.0
--
J005627.57-002108.1
14.11
-0.35
0.08
0.08
0.9857
3.66
14.82
0.04
31.3
--
--
--
--
--
--
--
--
--
no
no
433834423123
14.115
-0.352
0.936
3.51
17.92
0.02
17.25
0.02
16.42
0.03
15.64
0.02
no
472469436506
14.115
-0.352
0.964
3.39
17.2
0.02
16.41
0.02
15.6
0.02
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2361
742830101
14.115
-0.16
5.8
291.7
0
no
no
2.02
0.5
26.23
26.34
7.29
2.78
15.92
7.4
8.61
1.74
49.88
33.0
-999.0
-999.0
-999.0
no
1237666339187917237
14.115
-0.16
0.81
1.01
no
23.41
0.69
22.61
0.16
21.97
0.13
21.49
0.13
20.63
0.24
--
--
-999.0
--
J005627.65-000937.0
14.12
-0.16
0.13
0.13
0.9522
1.27
15.68
0.05
22.7
--
--
--
--
--
--
--
--
--
no
no
433834423565
14.115
-0.16
0.826
1.08
--
--
19.49
0.15
18.64
0.2
17.88
0.15
no
472469432977
14.115
-0.16
0.831
1.24
19.9
0.17
19.06
0.2
17.93
0.16
no
2915238670318438835
14.115
-0.16
1.31
--
0.76
1.61
22.64
0.32
--
--
FIRST J005627.5-000936
14.115
-0.16
1.17
8.64
0.11
--
--
--
--
--
--
--
--
--
--
--
0
2362
742830101
14.142
-0.442
3.4
49.1
0
no
no
0.95
0.26
22.03
20.45
0.0
0.0
0.0
0.0
3.48
0.83
36.45
20.87
-999.0
-999.0
-999.0
no
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
-999.0
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
no
2918862660643598899
14.141
-0.441
0.95
--
0.79
6.21
22.09
0.17
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2363
742830101
14.154
-0.448
2.1
49.1
0
no
no
7.25
0.63
177.33
389.08
17.33
2.73
73.38
62.06
24.68
1.83
273.08
402.95
43.8
44.17
44.33
no
1237666338651046108
14.155
-0.447
1.0
1.79
no
20.39
0.05
19.99
0.02
19.91
0.02
19.41
0.02
19.11
0.04
779144212938516480
QSO
0.474
11
J005637.10-002649.8
14.15
-0.45
0.07
0.07
0.9952
1.87
14.69
0.03
33.0
--
--
--
--
--
--
--
--
--
no
no
433836362494
14.155
-0.447
0.977
1.81
18.22
0.04
17.87
0.04
17.17
0.05
16.25
0.03
no
472469438358
14.155
-0.447
0.987
1.84
17.81
0.03
16.96
0.03
16.06
0.03
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2364
742830101
14.162
-0.357
5.2
145.3
0
no
no
0.69
0.2
19.99
17.08
0.0
0.0
0.0
0.0
2.16
0.59
28.08
14.19
44.25
0.0
0.0
no
1237663783666712923
14.163
-0.357
0.97
2.12
no
21.3
0.08
21.12
0.03
21.29
0.05
20.9
0.05
20.78
0.16
--
QSO
1.858
1
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
472469436589
14.163
-0.357
0.878
1.98
20.23
0.23
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2365
742830101
14.162
0.038
4.0
224.1
0
no
no
1.64
0.44
22.75
21.26
0.0
0.0
0.0
0.0
3.95
1.15
25.07
12.93
44.44
0.0
0.0
no
1237663784203583728
14.162
0.039
0.97
6.14
no
19.76
0.03
19.45
0.01
19.41
0.01
19.19
0.01
19.19
0.05
780344880525240320
QSO
1.577
11
J005638.88+000222.2
14.16
0.04
0.17
0.18
0.934
6.24
16.2
0.07
15.7
--
--
--
--
--
--
--
--
--
no
no
433832563084
14.162
0.04
0.843
6.21
18.88
0.05
18.5
0.06
17.78
0.1
17.45
0.1
no
472447126149
14.162
0.04
0.907
6.28
18.28
0.05
17.6
0.05
17.44
0.11
no
6476213785057036472
14.162
0.04
0.64
--
0.92
6.44
21.25
0.08
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2366
742830101
14.163
-0.4
3.8
29.8
0
no
no
1.24
0.38
17.36
17.26
0.0
0.0
0.0
0.0
2.96
0.98
20.61
9.98
-999.0
-999.0
-999.0
no
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
-999.0
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
433836363120
14.164
-0.399
0.877
2.61
--
--
--
--
--
--
18.11
0.19
no
472469437466
14.164
-0.399
0.888
2.46
20.4
0.27
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
2367
742830101
14.17
-0.244
2.7
283.6
0
no
no
0.89
0.2
33.01
26.73
0.0
0.0
0.0
0.0
2.68
0.61
44.18
19.81
-999.0
-999.0
-999.0
no
1237663783666713322
14.17
-0.244
0.97
0.88
no
23.92
0.64
22.77
0.14
22.15
0.12
22.05
0.15
21.94
0.48
--
--
-999.0
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
472469459857
14.17
-0.244
0.969
0.72
--
--
19.3
0.24
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
5211
747440101
27.985
-0.049
3.5
298.5
0
no
no
0.94
0.17
42.03
47.44
1.8
0.63
14.24
9.81
2.99
0.48
60.55
58.79
43.87
0.0
44.38
no
1237666407917813801
27.985
-0.049
0.99
0.22
no
19.57
0.03
19.6
0.01
19.46
0.01
19.49
0.02
19.58
0.07
787013142797379584
QSO
1.166
11
J015156.46-000255.6
27.99
-0.05
0.09
0.09
0.9779
0.41
15.61
0.04
25.2
14.26
0.04
26.1
11.35
0.17
6.5
8.26
0.22
5.0
no
no
433832463003
27.985
-0.049
0.948
0.56
18.77
0.06
18.81
0.12
18.07
0.13
17.28
0.1
no
472468136661
27.985
-0.049
0.953
0.55
19.07
0.06
18.33
0.06
17.49
0.08
no
3779155742589725600
27.985
-0.049
0.52
0.73
0.99
1.66
20.05
0.03
22.94
0.18
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5212
747440101
27.987
-0.564
3.6
289.2
0
no
no
1.02
0.36
11.78
13.05
0.0
0.0
0.0
0.0
4.57
1.28
22.74
17.28
-999.0
-999.0
-999.0
no
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
-999.0
--
J015156.95-003350.2
27.99
-0.56
0.14
0.14
0.9854
1.84
15.98
0.05
21.4
15.37
0.1
11.1
12.85
0.54
2.0
9.18
--
-2.0
no
no
433836104298
27.987
-0.563
0.917
3.39
19.31
0.11
--
--
18.05
0.12
17.41
0.09
no
--
--
--
--
--
--
--
--
--
--
--
no
3779155742587621381
27.988
-0.564
0.68
--
0.95
3.21
21.54
0.09
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5213
747440101
27.994
0.063
3.3
138.7
0
no
no
0.99
0.26
22.0
20.86
0.0
0.0
0.0
0.0
3.06
0.73
30.38
20.14
-999.0
-999.0
-999.0
no
1237663784209613117
27.994
0.064
0.97
2.22
no
22.22
0.18
21.43
0.04
20.81
0.03
20.23
0.03
19.78
0.08
--
--
-999.0
--
J015158.57+000348.8
27.99
0.06
0.13
0.13
0.9856
2.31
15.93
0.05
22.2
15.64
0.11
9.6
12.09
0.3
3.6
9.39
--
-0.8
no
no
433832462768
27.994
0.064
0.945
2.19
19.05
0.08
18.48
0.09
17.79
0.1
16.93
0.07
no
472447967913
27.994
0.064
0.971
2.12
18.54
0.04
17.74
0.04
17.03
0.06
no
3784609320263485369
27.994
0.064
0.7
1.06
0.89
2.26
22.77
0.16
24.21
0.38
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5214
747440101
27.997
0.134
2.7
167.0
0
no
no
0.9
0.2
30.32
38.29
0.0
0.0
0.0
0.0
2.44
0.49
36.95
35.57
44.55
0.0
44.98
no
1237663784209678565
27.997
0.134
0.96
3.21
no
22.35
0.19
21.74
0.05
21.7
0.06
21.67
0.08
21.06
0.21
4765066332620910592
QSO
2.223
11
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
472447965676
27.997
0.134
0.911
3.2
20.56
0.22
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5215
747440101
28.0
-0.415
2.5
174.1
0
no
no
1.15
0.25
28.81
43.1
0.0
0.0
0.0
0.0
3.03
0.64
34.1
33.55
-999.0
-999.0
-999.0
no
1237663783672807520
28.0
-0.415
0.99
2.38
no
19.81
0.03
17.28
0.01
16.0
0.01
15.27
0.01
14.8
0.01
--
--
-999.0
--
J015200.06-002454.0
28.0
-0.42
0.04
0.04
0.9934
2.37
12.6
0.02
46.3
12.55
0.02
45.0
11.7
0.21
5.1
9.14
--
-0.2
no
no
433836104605
28.0
-0.415
0.978
2.29
14.06
0.0
13.49
0.0
13.04
0.0
12.8
0.0
no
472468147807
28.0
-0.415
0.991
2.25
13.52
0.0
12.94
0.0
12.72
0.0
no
3779155742587623450
28.0
-0.415
0.74
--
0.93
1.55
22.7
0.17
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5216
747440101
28.005
-0.137
3.0
83.6
0
no
no
0.87
0.21
24.67
29.19
0.0
0.0
0.0
0.0
2.31
0.53
29.77
27.15
-999.0
-999.0
-999.0
no
1237666407917813942
28.005
-0.137
0.97
0.6
no
22.17
0.2
22.28
0.09
21.81
0.09
21.58
0.1
21.19
0.26
--
--
-999.0
--
J015201.15-000813.2
28.0
-0.14
0.25
0.26
0.978
0.62
16.91
0.09
12.0
16.13
0.17
6.6
12.48
--
0.2
9.14
--
-0.4
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
472468139171
28.005
-0.137
0.968
0.3
19.91
0.12
19.04
0.12
18.27
0.15
no
3779155742587627301
28.005
-0.137
1.65
--
0.75
1.1
23.85
0.39
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5217
747440101
28.007
-0.463
3.5
141.3
0
no
no
0.77
0.25
15.35
14.8
0.0
0.0
0.0
0.0
2.29
0.64
20.32
17.07
-999.0
-999.0
-999.0
no
1237666407380943336
28.007
-0.464
0.96
2.13
no
23.05
0.48
22.84
0.16
22.13
0.13
21.66
0.13
21.01
0.25
--
--
-999.0
--
J015201.74-002748.6
28.01
-0.46
0.13
0.13
0.9201
1.87
15.94
0.05
21.4
15.13
0.08
13.9
12.74
0.54
2.0
8.65
--
1.8
no
no
433836104787
28.007
-0.464
0.931
2.2
--
--
19.28
0.19
18.34
0.15
17.64
0.12
no
472468149254
28.007
-0.464
0.786
1.94
19.41
0.07
18.61
0.08
17.67
0.09
no
3779155742587622758
28.007
-0.463
1.27
--
0.88
1.62
22.82
0.24
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5218
747440101
28.011
0.371
3.6
309.4
0
no
no
0.53
0.16
15.05
16.46
0.0
0.0
0.0
0.0
1.41
0.43
18.01
13.26
-999.0
-999.0
-999.0
no
--
28.012
0.371
0.86
4.22
yes
25.09
0.44
24.3
0.11
23.89
0.1
22.89
0.07
22.81
0.27
--
--
-999.0
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
no
no
--
--
--
--
--
--
--
--
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5219
747440101
28.024
-0.263
3.1
242.2
0
no
no
0.85
0.25
16.62
18.57
0.0
0.0
0.0
0.0
2.53
0.71
22.43
15.99
-999.0
-999.0
-999.0
no
1237663783672807718
28.024
-0.263
0.99
1.88
no
21.31
0.08
21.39
0.04
21.02
0.04
20.89
0.05
20.3
0.11
--
--
-999.0
--
J015205.80-001547.2
28.02
-0.26
0.15
0.15
0.9823
2.3
16.14
0.06
19.4
15.57
0.11
10.2
12.18
--
1.5
9.08
0.52
2.1
no
no
433834205134
28.024
-0.263
0.757
1.84
--
--
18.93
0.14
18.42
0.18
17.62
0.15
no
472468142881
28.024
-0.263
0.787
1.72
19.15
0.06
18.65
0.08
17.74
0.09
no
3779155742589722957
28.024
-0.262
0.67
0.64
0.98
2.78
21.28
0.07
22.19
0.11
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
5220
747440101
28.044
0.134
4.1
167.0
0
no
no
0.79
0.22
20.02
17.82
0.0
0.0
0.0
0.0
2.14
0.57
24.03
17.67
-999.0
-999.0
-999.0
no
1237663784209678589
28.043
0.135
0.97
3.59
no
20.58
0.12
19.8
0.03
18.78
0.02
18.32
0.02
18.05
0.05
--
--
-999.0
--
J015210.30+000804.8
28.04
0.13
0.11
0.12
0.9773
3.51
15.69
0.04
25.2
15.45
0.1
10.6
12.16
--
1.4
8.9
--
0.5
no
no
433830737812
28.043
0.135
0.911
3.94
18.55
0.05
17.98
0.05
17.29
0.06
16.63
0.06
no
472447965668
28.043
0.135
0.946
3.74
17.88
0.02
17.22
0.03
16.56
0.04
no
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
--
0
----


+*In[6]:*+
[source, ipython3]
----
cat_uk = ATable.read('uks82/ukidss.fits',columns=['RA','DEC'])
----


+*In[15]:*+
[source, ipython3]
----
cat_uk.metatable
----


+*Out[15]:*+
----
description
unit
ucd
dtype
nil
colname
RA
unknown
()
float64
None
DEC
unknown
()
float64
None
----


+*In[17]:*+
[source, ipython3]
----
from astropy.coordinates import Angle
ra = Angle(cat_uk['RA'],'rad').to('deg')
dec= Angle(cat_uk['DEC'],'rad').to('deg')
----


+*In[18]:*+
[source, ipython3]
----
cat_uk['RA'] = ra
cat_uk['DEC'] = dec
----


+*In[21]:*+
[source, ipython3]
----
cat_uk
----


+*Out[21]:*+
----
<ATable length=3501552>
RA
DEC
deg
deg
float64
float64
344.989744243
1.2399620675
345.072243834
1.24008030105
345.02833517
1.240398902
345.02904828
1.24094234799
345.045858353
1.24102154323
345.009139562
1.24146907595
344.901459725
1.24213322914
344.993263786
1.24286858721
344.881007618
1.24328732306
...
...
316.424155675
1.24810153286
316.430048762
1.24855215438
316.444278524
1.24909158423
316.457856242
1.24973021976
316.288146807
1.24395895055
316.478105197
1.24376225754
316.351084815
1.24526706361
316.333799484
1.24668968512
316.28118499
1.24718442192
316.311320316
1.24787590201
----


+*In[22]:*+
[source, ipython3]
----
from booq import plot
----


+*Out[22]:*+
----
/home/chbrandt/.conda/envs/booq/lib/python3.6/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: 
The bokeh.charts API has moved to a separate 'bkcharts' package.

This compatibility shim will remain until Bokeh 1.0 is released.
After that, if you want to use this API you will have to install
the bkcharts package explicitly.

  warn(message)
----


+*In[ ]:*+
[source, ipython3]
----

----
